ctutils: enforce `Bytes*` trait usage at compile-time (#1364)
The `Bytes*` traits exist because we don't have specialization[1] and
the generic implementation of these traits for `[T]` and `[T; N]` will
operate a byte-at-a-time on byte slices and byte arrays, when efficient
implementations from the `cmov` crate can instead perform the same
operations a word-at-a-time.

Adds != 1 const size assertions for `T` in the impls of `CtAssign`,
`CtEq` for `[T]` and `[T; N]` as well as the `CtSelect` impl for `[T;
N]` which cause a compile-time error if they're requested to be used
with 1-byte values:

error[E0080]: evaluation panicked: use `BytesCtEq::bytes_ct_eq` when
working with byte-sized values
      --> ctutils/src/traits/ct_eq.rs:81:13
       |
    81 | /             assert!(
    82 | |                 size_of::<T>() != 1,
83 | | "use `BytesCtEq::bytes_ct_eq` when working with byte-sized
values"
    84 | |             );
| |_____________^ evaluation of `<[u8] as
traits::ct_eq::CtEq>::ct_eq::{constant#0}` failed here

Each of them has been configured with a message that steers the user
instead towards the appropriate `BytesCt*` trait to use instead.

[1]: https://rust-lang.github.io/rfcs/1210-impl-specialization.html